repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-merge-conflict
      - id: debug-statements
      - id: mixed-line-ending
        exclude: |
          (?x)^(
          data/ooa-outgroups/ooa.chr21.ts |
          data/ooa-outgroups/ooa.chr22.ts
          )$
      - id: check-case-conflict
      - id: check-yaml
      - id: trailing-whitespace
        exclude: |
          (?x)^(
          data/ooa-outgroups/ooa.chr21.ts |
          data/ooa-outgroups/ooa.chr22.ts
          )$
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.12.0
    hooks:
      - id: reorder-python-imports
        args: [--application-directories=python,
               --unclassifiable-application-module=_tskit]
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
      - id: pyupgrade
        args: [--py3-plus, --py37-plus]
  - repo: https://github.com/psf/black
    rev: 23.10.1
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args: [--max-line-length=89]
        additional_dependencies: ["flake8-bugbear==22.3.23", "flake8-builtins==1.5.3"]
  - repo: https://github.com/asottile/blacken-docs
    rev: 1.16.0
    hooks:
      - id: blacken-docs
        args: [--skip-errors]
        additional_dependencies: [black==22.3.0]
        language_version: python3
  - repo: local
    hooks:
      - id: lint
        name: Snakemake lint monkeyflower workflow
        entry: snakemake --lint text --directory data/monkeyflower -s
        language: system
        log_file: 'snakemake-monkeyflower-lint.txt'
        files: 'data/monkeyflower/workflow/Snakefile'
